import Login from "@/components/auth/LoginForm";
import Register from "@/components/auth/AuthForm";
import { setUser } from "@/store/actions";
import { selectAuthState } from "@/store/authSlice";
import axios from "axios";
import { useDispatch, useSelector } from "react-redux";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  // const user = useSelector(selectAuthState);
  // const dispatch = useDispatch();
  
  // async function logout() {
  //     await axios.post("/api/users/logout")
  //     dispatch(setUser(null))
  // }

  return <div>
      {/* { user ? 
      <button onClick={logout}>Log Out</button> : 
      <div>
          <Login></Login>
          <Register></Register>
      </div>
      } */}
      { children }
  </div>

}
