import './globals.css'
import { Inter } from 'next/font/google'

import AuthForm from "../app/components/auth/AuthForm";
import LoginForm from "../app/components/auth/LoginForm";
import DiscussionForm from "../app/components/discussion/DiscussionForm"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthForm />
        <LoginForm />
        <DiscussionForm></DiscussionForm>
        {children}
      </body>
    </html>
  )
}
